<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateSalesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('sales', function (Blueprint $table) {
            $table->increments('id');
            $table->string('FiWipStatusCode', 1);
            $table->string('FinInstituteCode', 32);
            $table->decimal('FinanceAmt', 15, 2);
            $table->decimal('FinanceCharge', 15, 2);
            $table->string('FinanceSource', 10);
            $table->date('FirstPayDate');
            $table->decimal('BackGross', 15, 2);
            $table->decimal('BackWeOwes', 15, 2);
            $table->decimal('BalloonAmount', 15, 2);
            $table->decimal('BankFee', 12, 2);
            $table->decimal('BaseResidual', 15, 2);
            $table->string('BodyStyle', 12);
            $table->decimal('BonusSP1', 15, 2);
            $table->decimal('BonusSP2', 15, 2);
            $table->decimal('BonusSP3', 15, 2);
            $table->string('Branch', 17);
            $table->string('BusinessPhone', 15);
            $table->decimal('BuyRateAPR', 15, 2);
            $table->decimal('BuyRateAddOn', 15, 4);
            $table->decimal('BuyRateLFM', 15, 5);
            $table->decimal('BuyRateLMF', 15, 5);
            $table->decimal('CLCost', 15, 2);
            $table->decimal('CLIncome', 15, 2);
            $table->decimal('CLPremium', 15, 2);
            $table->string('CRMClosingMgrId', 10);
            $table->string('CRMClosingMgrName', 18);
            $table->string('CRMFIMgrId', 10);
            $table->string('CRMFIMgrName', 18);
            $table->string('CRMFlag', 1);
            $table->string('VIN', 17);
            $table->decimal('VehInventoryCompany', 15, 2);
            $table->decimal('VehSaleCompany', 15, 2);
            $table->decimal('VehicleMileage', 15, 0);
            $table->string('WAQNumber', 15);
            $table->decimal('WarrantyFee', 12, 2);
            $table->decimal('WeOweBackSaleTotal', 15, 2);
            $table->decimal('WeOweCostTotal', 15, 2);
            $table->decimal('WeOweFrontGrossSales', 15, 2);
            $table->decimal('WeOweSaleTotal', 15, 2);
            $table->decimal('Year', 4, 0);
            $table->string('ZipOrPostalCode', 10);
            $table->decimal('SecurityDepositAmount', 15, 2);
            $table->decimal('SellRateLMF', 15, 2);
            $table->decimal('LeaseEndPercentageRate', 15, 2);
            $table->decimal('LeaseEndValue', 15, 2);
            $table->decimal('LeaseMileageAllowance', 6, 0);
            $table->decimal('LeasePayment', 15, 2);
            $table->string('LeaseType', 8);
            $table->decimal('LevelizedLifeAmount', 15, 2);
            $table->decimal('LevelizedLifeIncome', 15, 2);
            $table->string('LienHolderAddress', 50);
            $table->string('LienHolderCity', 50);
            $table->string('LienHolderName', 50);
            $table->string('LienHolderName2', 50);
            $table->string('LienHolderPhone', 15);
            $table->string('LienHolderState', 2);
            $table->string('LienHolderZip', 10);
            $table->decimal('AddToCapCostFee5Amount', 15, 2);
            $table->decimal('AddToCapCostFee5CostAmount', 15, 2);
            $table->string('AddToCapCostFee5Name', 22);
            $table->decimal('AddToCapCostFee6Amount', 15, 2);
            $table->string('AddToCapCostFee6CostAmount', 15, 2);
            $table->string('AddToCapCostFee6Name', 22);
            $table->decimal('AddToCapCostFee7Amount', 15, 2);
            $table->decimal('AddToCapCostFee7CostAmount', 15, 2);
            $table->string('AddToCapCostFee7Name', 22);
            $table->string('Address', 50);
            $table->decimal('AdjustedCapCost', 15, 2);
            $table->decimal('AdjustedCostofVehicle', 15, 2);
            $table->decimal('AdjustmentsDealerDefined', 10, 2);
            $table->decimal('AdjustmentsROPO', 10, 2);
            $table->decimal('AdjustmentsStandard', 10, 2);
            $table->decimal('Age', 15, 0);
            $table->decimal('AmountDueAtStart', 15, 2);
            $table->decimal('AnnualFee1Amount', 15, 2);
            $table->string('AnnualFee1Name', 22);
            $table->decimal('AnnualFee2Amount', 15, 2);
            $table->string('AnnualFee2Name', 22);
            $table->decimal('AnnualFee3Amount', 15, 2);
            $table->string('AnnualFee3Name', 22);
            $table->decimal('AnnualFee4Amount', 15, 2);
            $table->string('AnnualFee4Name', 22);
            $table->decimal('AnnualFee5Amount', 15, 2);
            $table->string('AnnualFee5Name', 22);
            $table->decimal('Insurance1Term', 15, 0);
            $table->decimal('Insurance2Deductible', 15, 2);
            $table->decimal('TotalInitFees', 15, 2);
            $table->decimal('TotalInsurancePremiums', 15, 2);
            $table->decimal('TotalOfMonthlyPayments', 15, 2);
            $table->decimal('TotalOptionsFees', 15, 2);
            $table->decimal('TotalTaxableFees', 15, 2);
            $table->decimal('TotalTradeAllowance', 15, 2);
            $table->decimal('TotalTradesACV', 15, 2);
            $table->decimal('TotalTradesNet', 15, 2);
            $table->decimal('TotalTradesPayoff', 15, 2);
            $table->decimal('Trade1ACV', 15, 2);
            $table->string('Trade1Color', 30);
            $table->decimal('Trade1Gross', 15, 2);
            $table->string('Trade1Make', 10);
            $table->string('Trade1MakeName', 30);
            $table->string('Trade1Mileage', 30);
            $table->decimal('PurchaseMBICost', 15, 2);
            $table->string('Color', 20);
            $table->decimal('CommissionPack', 15, 2);
            $table->date('ContractDate');
            $table->decimal('CostPrice', 15, 2);
            $table->string('County', 20);
            $table->string('CustNo', 17);
            $table->string('CustOrCompanyCode', 2);
            $table->decimal('CustomerCashDown', 15, 2);
            $table->string('CustomerComments', 7500);
            $table->decimal('InitialCapCost', 15, 2);
            $table->decimal('InitialFee10Amount', 15, 2);
            $table->decimal('InitialFee10CostAmount', 15, 2);
            $table->string('InitialFee10Name', 22);
            $table->decimal('InitialFee1Amount', 15, 2);
            $table->decimal('InitialFee1CostAmount', 15, 2);
            $table->string('InitialFee1Name', 22);
            $table->decimal('InitialFee2Amount', 15, 2);
            $table->decimal('InitialFee2CostAmount', 15, 2);
            $table->string('InitialFee2Name', 22);
            $table->decimal('InitialFee3Amount', 15, 2);
            $table->decimal('InitialFee3CostAmount', 15, 2);
            $table->string('InitialFee3Name', 22);
            $table->decimal('InitialFee4Amount', 15, 2);
            $table->decimal('InitialFee4CostAmount', 15, 2);
            $table->string('InitialFee4Name', 22);
            $table->string('DealNo', 10);
            $table->string('DealSource', 15);
            $table->string('DealType', 13);
            $table->decimal('Insurance2Limit', 15, 2);
            $table->decimal('Insurance2LimitMiles', 15, 0);
            $table->string('Insurance2Name', 21);
            $table->decimal('Insurance2Term', 15, 2);
            $table->decimal('Insurance3Deductible', 15, 2);
            $table->decimal('Insurance3Limit', 15, 2);
            $table->decimal('Insurance3LimitMiles', 15, 0);
            $table->string('Insurance3Name', 21);
            $table->decimal('Insurance3Term', 15, 0);
            $table->decimal('InsuranceCommDlr', 15, 2);
            $table->string('InsuranceTypeCode', 30);
            $table->decimal('LSTGSTAmount', 15, 2);
            $table->decimal('LSTGSTRate', 15, 4);
            $table->string('LSTGSTRateFlat', 15);
            $table->decimal('LastPayAmount', 15, 2);
            $table->date('LastPayDate');
            $table->decimal('OutTheDoorPrice', 12, 2);
            $table->decimal('PaymentAmt', 15, 2);
            $table->string('PaymentCode', 10);
            $table->string('PaymentStyle', 10);
            $table->decimal('Payments', 8, 0);
            $table->date('PickupDate1');
            $table->date('PickupDate2');
            $table->date('PickupDate3');
            $table->decimal('PickupPay1', 15, 2);
            $table->decimal('PickupPay2', 15, 2);
            $table->decimal('PickupPay3', 15, 2);
            $table->decimal('ExtWarrantyExpMilesLease', 15, 0);
            $table->decimal('ExtWarrantyTermLease', 15, 0);
            $table->string('FIDealType', 13);
            $table->decimal('FIIncome', 15, 2);
            $table->string('FIMgr1', 17);
            $table->string('FIMgr2', 17);
            $table->decimal('FeeOption10Amount', 15, 2);
            $table->decimal('FeeOption10Cost', 15, 2);
            $table->string('FeeOption10Name', 24);
            $table->decimal('FeeOption1Amount', 15, 2);
            $table->decimal('FeeOption1Cost', 15, 2);
            $table->string('FeeOption1Name', 24);
            $table->decimal('FeeOption2Amount', 15, 2);
            $table->decimal('FeeOption2Cost', 15, 2);
            $table->string('FeeOption2Name', 24);
            $table->decimal('RebateAmount', 15, 2);
            $table->string('SLSDealType', 13);
            $table->decimal('SalePriceWithWeOwes', 15, 2);
            $table->string('SaleType', 8);
            $table->string('SalesAccount', 17);
            $table->date('SalesDate');
            $table->string('SalesMgr', 17);
            $table->string('Salesperson1', 17);
            $table->string('Salesperson2', 17);
            $table->string('Salesperson3', 17);
            $table->string('CRMSP1Id', 10);
            $table->string('CRMSP1Name', 18);
            $table->string('CRMSP2Id', 10);
            $table->string('CRMSP2Name', 18);
            $table->string('CRMSP3Id', 10);
            $table->string('CRMSP3Name', 18);
            $table->string('CRMSaleType', 3);
            $table->string('CRMSalesMgrId', 10);
            $table->string('CRMSalesMgrName', 18);
            $table->string('CalcMethod', 20);
            $table->decimal('CashCapReduction', 15, 2);
            $table->decimal('CashDown', 15, 2);
            $table->decimal('CashPrice', 15, 2);
            $table->string('City', 50);
            $table->string('ClosingMgr', 17);
            $table->string('CoAddress', 50);
            $table->string('CoBusinessPhone', 15);
            $table->string('CoBuyer', 50);
            $table->string('CoCity', 50);
            $table->string('CoCounty', 20);
            $table->string('CoCustNo', 17);
            $table->string('CoHomePhone', 15);
            $table->string('CoName1', 25);
            $table->string('CoState', 2);
            $table->string('CoZipOrPostalCode', 10);
            $table->decimal('DepositAmount', 15, 2);
            $table->string('DepositType', 12);
            $table->decimal('DueOnDelivery', 15, 2);
            $table->decimal('FrontEndGrossProfit', 15, 2);
            $table->decimal('FrontGross', 15, 2);
            $table->decimal('FrontWeOwes', 15, 2);
            $table->decimal('FrontWeOwesGrossCost', 15, 2);
            $table->decimal('FrontWeOwesGrossSales', 15, 2);
            $table->decimal('GrossProfit', 15, 2);
            $table->string('HomePhone',15);
            $table->string('HostItemID', 40);
            $table->decimal('IncentiveDealer', 12, 2);
            $table->decimal('IncentiveProgram', 12, 2);
            $table->string('MBICarrier', 20);
            $table->decimal('MBICost', 15, 2);
            $table->decimal('MBIDeductible', 15, 2);
            $table->string('MBIEligComment', 20);
            $table->string('MBIEligFlag', 2);
            $table->decimal('MBIFee', 15, 2);
            $table->decimal('MBIIncome', 15, 2);
            $table->decimal('MBILimit', 6, 0);
            $table->string('MBILimitMax', 6);
            $table->string('MBIName', 25);
            $table->decimal('MBITerm', 15, 0);
            $table->decimal('MSRP', 15, 2);
            $table->string('Make', 10);
            $table->string('MakeName', 30);
            $table->string('MbiPolicyNo', 20);
            $table->decimal('MileageExpected', 15, 0);
            $table->decimal('MileagePenaltyAmount', 15, 2);
            $table->decimal('MileagePenaltyRate', 15, 2);
            $table->string('State', 2);
            $table->string('StockNo', 17);
            $table->decimal('SurplusCash', 15, 2);
            $table->decimal('Tax', 15, 2);
            $table->decimal('Tax1Amount', 15, 2);
            $table->decimal('Tax1Base', 15, 2);
            $table->string('Tax1Name', 22);
            $table->decimal('AHCost', 15, 2);
            $table->decimal('AHIncome', 15, 2);
            $table->decimal('AHPremium', 15, 2);
            $table->decimal('APR', 15, 2);
            $table->string('AccountingAccount', 17);
            $table->date('AccountingDate');
            $table->decimal('AddToCapAmount', 15, 2);
            $table->decimal('AddToCapCostFee1Amount', 15, 2);
            $table->decimal('AddToCapCostFee1CostAmount', 15, 2);
            $table->string('AddToCapCostFee1Name', 22);
            $table->decimal('AddToCapCostFee2Amount', 15, 2);
            $table->decimal('AddToCapCostFee2CostAmount', 15, 2);
            $table->string('AddToCapCostFee2Name', 22);
            $table->decimal('AddToCapCostFee3Amount', 15, 2);
            $table->decimal('AddToCapCostFee3CostAmount', 15, 2);
            $table->string('AddToCapCostFee3Name', 22);
            $table->decimal('AddToCapCostFee4Amount', 15, 2);
            $table->decimal('AddToCapCostFee4CostAmount', 15, 2);
            $table->string('AddToCapCostFee4Flag', 30);
            $table->string('AddToCapCostFee4Name', 22);
            $table->string('Email1', 250);
            $table->string('Email1Desc', 15);
            $table->string('Email2', 250);
            $table->string('Email2Desc', 15);
            $table->string('Email3', 250);
            $table->string('Email3Desc', 15);
            $table->string('ErrorLevel', 1);
            $table->string('ErrorMessage', 80);
            $table->decimal('Miscellaneous1', 15, 2);
            $table->decimal('Miscellaneous10', 15, 2);
            $table->decimal('Miscellaneous2', 15, 2);
            $table->decimal('Miscellaneous3', 15, 2);
            $table->decimal('Miscellaneous4', 15, 2);
            $table->decimal('Miscellaneous5', 15, 2);
            $table->decimal('Miscellaneous6', 15, 2);
            $table->decimal('Miscellaneous7', 15, 2);
            $table->decimal('Miscellaneous8', 15, 2);
            $table->decimal('Miscellaneous9', 15, 2);
            $table->string('Model', 10);
            $table->string('ModelName', 30);
            $table->string('ModelNo', 20);
            $table->string('ModelType', 12);
            $table->string('Name', 50);
            $table->string('Name1', 50);
            $table->decimal('NetTrade1', 15, 2);
            $table->decimal('NetTrade2', 15, 2);
            $table->decimal('OptionsCommDlr', 15, 2);
            $table->decimal('Term', 4, 0);
            $table->decimal('TexasGAPInsuranceAmount', 15, 2);
            $table->decimal('TotalAnnFees', 15, 2);
            $table->decimal('TotalCapReduction', 15, 2);
            $table->decimal('TotalCashSurplus', 15, 2);
            $table->decimal('TotalDown', 15, 2);
            $table->decimal('TotalFinancedFeeOptions', 15, 2);
            $table->decimal('Ins3Cost', 15, 2);
            $table->decimal('Ins3Fee', 15, 2);
            $table->decimal('Ins3Income', 15, 2);
            $table->decimal('Insurance1Deductible', 15, 2);
            $table->decimal('Insurance1Limit', 15, 2);
            $table->decimal('Insurance1LimitMiles', 15, 0);
            $table->string('Insurance1Name', 21);
            $table->decimal('TotalGross', 15, 2);
            $table->decimal('Tax1Rate', 15, 2);
            $table->decimal('Tax2Amount', 15, 2);
            $table->string('Tax2Name', 22);
            $table->decimal('Tax2Rate', 15, 2);
            $table->decimal('Tax3Amount', 15, 2);
            $table->string('Tax3Name', 22);
            $table->decimal('Tax3Rate', 15, 2);
            $table->decimal('Tax4Amount', 15, 2);
            $table->string('Tax4Name', 22);
            $table->decimal('Tax4Rate', 15, 2);
            $table->string('Trade1Model', 10);
            $table->string('Trade1ModelName', 30);
            $table->string('Trade1ModelNo', 30);
            $table->string('Trade1ModelType', 30);
            $table->decimal('Trade1PayOff', 15, 2);
            $table->string('Trade1Stock', 17);
            $table->string('Trade1Style', 30);
            $table->string('Trade1VIN', 17);
            $table->decimal('Trade1Year', 4, 0);
            $table->decimal('Trade2ACV', 15, 2);
            $table->string('Trade2Color', 30);
            $table->decimal('Trade2Gross', 15, 2);
            $table->string('Trade2Make', 10);
            $table->string('Trade2MakeName', 30);
            $table->string('Trade2Mileage', 30);
            $table->string('Trade2Model', 10);
            $table->string('Trade2ModelName', 30);
            $table->string('Trade2ModelNo', 30);
            $table->string('Trade2ModelType', 30);
            $table->decimal('Trade2PayOff', 15, 2);
            $table->string('Trade2Stock', 17);
            $table->string('Trade2Style', 30);
            $table->string('Trade2VIN', 17);
            $table->decimal('Trade2Year', 4, 0);
            $table->decimal('USLuxuryExciseTaxAmount', 15, 2);
            $table->decimal('FeeOption3Amount', 15, 2);
            $table->decimal('FeeOption3Cost', 15, 2);
            $table->string('FeeOption3Name', 24);
            $table->decimal('FeeOption4Amount', 15, 2);
            $table->decimal('FeeOption4Cost', 15, 2);
            $table->string('FeeOption4Name', 24);
            $table->decimal('FeeOption5Amount', 15, 2);
            $table->decimal('FeeOption5Cost', 15, 2);
            $table->string('FeeOption5Name', 24);
            $table->decimal('FeeOption6Amount', 15, 2);
            $table->decimal('FeeOption6Cost', 15, 2);
            $table->string('FeeOption6Name', 24);
            $table->decimal('FeeOption7Amount', 15, 2);
            $table->decimal('FeeOption7Cost', 15, 2);
            $table->string('FeeOption7Name', 24);
            $table->decimal('FeeOption8Amount', 15, 2);
            $table->decimal('FeeOption8Cost', 15, 2);
            $table->string('FeeOption8Name', 24);
            $table->decimal('FeeOption9Amount', 15, 2);
            $table->decimal('FeeOption9Cost', 15, 2);
            $table->string('FeeOption9Name', 24);
            $table->decimal('InitialFee5Amount', 15, 2);
            $table->decimal('InitialFee5CostAmount', 15, 2);
            $table->string('InitialFee5Name', 22);
            $table->decimal('InitialFee6Amount', 15, 2);
            $table->decimal('InitialFee6CostAmount', 15, 2);
            $table->string('InitialFee6Name', 22);
            $table->decimal('InitialFee7Amount', 15, 2);
            $table->decimal('InitialFee7CostAmount', 15, 2);
            $table->string('InitialFee7Name', 22);
            $table->decimal('InitialFee8Amount', 15, 2);
            $table->decimal('InitialFee8CostAmount', 15, 2);
            $table->string('InitialFee8Name', 22);
            $table->decimal('InitialFee9Amount', 15, 2);
            $table->decimal('InitialFee9CostAmount', 15, 2);
            $table->string('InitialFee9Name', 22);
            $table->decimal('Ins1Cost', 15, 2);
            $table->decimal('Ins1Fee', 15, 2);
            $table->decimal('Ins1Income', 15, 2);
            $table->decimal('Ins2Cost', 15, 2);
            $table->decimal('Ins2Fee', 15, 2);
            $table->decimal('Ins2Income', 15, 2);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sales');
    }
}
